version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    restart: on-failure
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  flask:
    image: devkyle4/docker-flask:version1
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

  streamlit:
    image: devkyle4/docker-streamlit:version1
    ports:
      - 8501:8501
    depends_on:
      - flask

volumes:
  esdata:
